# Generated by Django 5.1.5 on 2025-02-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_ziyaretci_tc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ziyaretci',
            name='durum',
            field=models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('GORUSME_BASLADI', 'Görüşme Başladı'), ('GORUSME_BITTI', 'Görüşme Bitti'), ('IPTAL', 'İptal Edildi')], default='BEKLIYOR', max_length=20, verbose_name='Durum'),
        ),
    ]
