# Generated by Django 5.1.5 on 2025-02-01 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ziyaretci_durum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ziyaretci',
            name='ziyaret_edilen',
        ),
        migrations.AddField(
            model_name='ziyaretci',
            name='kurum_ici_ziyaretci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurum_ici_ziyaretler', to=settings.AUTH_USER_MODEL, verbose_name='Kurum İçi Ziyaretçi'),
        ),
        migrations.AddField(
            model_name='ziyaretci',
            name='tur',
            field=models.CharField(choices=[('KURUM_ICI', 'Kurum İçi'), ('KURUM_DISI', 'Kurum Dışı')], default='KURUM_DISI', max_length=20, verbose_name='Tür'),
        ),
        migrations.AddField(
            model_name='ziyaretci',
            name='ziyaret_edilenler',
            field=models.ManyToManyField(related_name='ziyaret_edilenler', to=settings.AUTH_USER_MODEL, verbose_name='Ziyaret Edilenler'),
        ),
        migrations.AlterField(
            model_name='ziyaretci',
            name='durum',
            field=models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('GORUSME_BASLADI', 'Görüşme Başladı'), ('GORUSME_BITTI', 'Görüşme Bitti'), ('IPTAL', 'İptal')], default='BEKLIYOR', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='ziyaretci',
            name='kurum',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurum'),
        ),
        migrations.AlterField(
            model_name='ziyaretci',
            name='randevulu',
            field=models.BooleanField(default=False, verbose_name='Randevulu'),
        ),
    ]
