# Generated by Django 5.1.5 on 2025-02-01 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ziyaretci_ziyaret_edilen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ziyaretci',
            name='kurum_ici_ziyaretci',
        ),
        migrations.RemoveField(
            model_name='ziyaretci',
            name='ziyaret_edilenler',
        ),
        migrations.AddField(
            model_name='ziyaretci',
            name='kurum_ici_ziyaretciler',
            field=models.ManyToManyField(blank=True, related_name='kurum_ici_ziyaretler', to=settings.AUTH_USER_MODEL, verbose_name='Kurum İçi Ziyaretçiler'),
        ),
        migrations.AddField(
            model_name='ziyaretci',
            name='ziyaret_edilen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ziyaret_edilen', to=settings.AUTH_USER_MODEL, verbose_name='Ziyaret Edilen'),
        ),
    ]
