# Generated by Django 5.1.5 on 2025-02-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ziyaretci_ad_alter_ziyaretci_soyad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KurumDisiZiyaretci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('kurum_unvan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurum/Ünvan')),
            ],
            options={
                'verbose_name': 'Kurum Dışı Ziyaretçi',
                'verbose_name_plural': 'Kurum Dışı Ziyaretçiler',
            },
        ),
        migrations.RemoveField(
            model_name='ziyaretci',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='ziyaretci',
            name='kurum',
        ),
        migrations.RemoveField(
            model_name='ziyaretci',
            name='soyad',
        ),
        migrations.RemoveField(
            model_name='ziyaretci',
            name='telefon',
        ),
        migrations.AddField(
            model_name='ziyaretci',
            name='kurum_disi_ziyaretciler',
            field=models.ManyToManyField(blank=True, related_name='ziyaretler', to='core.kurumdisiziyaretci', verbose_name='Kurum Dışı Ziyaretçiler'),
        ),
    ]
