# Generated by Django 5.1.5 on 2025-02-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_kurumdisikatilimci_alter_toplanti_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toplanti',
            options={'verbose_name': 'Toplantı', 'verbose_name_plural': 'Toplantılar'},
        ),
    ]
