# Generated by Django 5.1.5 on 2025-01-30 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='external_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='meeting',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Düşük'), ('MEDIUM', 'Orta'), ('HIGH', 'Yüksek')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurrence_pattern',
            field=models.CharField(choices=[('NONE', 'Tekrar Yok'), ('DAILY', 'Günlük'), ('WEEKLY', 'Haftalık'), ('MONTHLY', 'Aylık')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='meeting_attachments/'),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='floor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='room_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visitor',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meetingroom'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Oluşturma'), ('UPDATE', 'Güncelleme'), ('DELETE', 'Silme'), ('STATUS_CHANGE', 'Durum Değişikliği')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
